# CANONICAL SOURCE — ai-control-plane/hooks/git/approve_governance_commit.ps1
#
# Run this manually, in your own terminal, AFTER staging protected-path changes
# and BEFORE running `git commit`. It is the only way to clear the protected-path
# pre-commit block — there is no environment-variable bypass any more.
#
# Why: $env:GOVERNANCE_APPROVED=1 could be set by the same shell session that an
# AI tool's Bash/PowerShell access runs in, making "approval" something the AI
# could grant itself in the same breath as the commit. A token file generated by
# a separate, deliberate run of this script is harder to fold into a single
# automated action, and it is scoped to the exact files staged at approval time
# (not a blanket "anything for N minutes" grant) and is single-use.
#
# This does not make self-approval cryptographically impossible — an agent with
# unrestricted shell access could still run this script. It raises the bar from
# "one env var in the same command" to "a distinct, separate, file-scoped action"
# and leaves an auditable timestamp. Treat it as friction + audit trail, not a
# hard security boundary.
#
# Hardening (2026-08-15, post fe09449 investigation):
# 1. -RepoRoot is now MANDATORY. Default "." caused silent no-op approval when
#    run from the wrong CWD (user's own run approved nothing while an agent run
#    from the right CWD succeeded — permission gradient inverted).
# 2. Empty staged set / no protected match now exits 1 with a loud alarm, not
#    the old mild "nothing to approve" (exit 0).
# 3. Token binds staged BLOB hashes (git ls-files -s) so approving file A then
#    committing different content of A is rejected at pre-commit time.
# 4. Every approval appends an audit line to .control-plane/.governance-audit.jsonl
#    (append-only, machine-readable) so the approval mechanism can produce
#    evidence about itself.
#
# Sequence reminder (lessons registry L1, 2026-08-29): 1) stage the exact
# files, 2) run THIS script, 3) run `git commit` immediately — the token is
# single-use, short-TTL, and any git command in between can change the
# staged set out from under the approval.
#
# .control-plane/ is intentionally untracked LOCAL state (token + audit
# log). This script creates it on demand (2026-08-29: the directory did not
# exist on a working install and the approval flow could not write its
# token). Durability policy: raw jsonl stays local; the monthly patrol
# commits a de-identified summary — see PROJECT_STATUS.md.

param(
  [Parameter(Mandatory = $true)][string]$RepoRoot,
  [string]$ProtectedPathsFile = ".control-plane/protected-paths.json",
  [int]$TtlMinutes = 10
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $RepoRoot)) {
  throw "RepoRoot does not exist: $RepoRoot"
}
$resolvedRepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
if (-not (Test-Path -LiteralPath (Join-Path $resolvedRepoRoot ".git"))) {
  # worktree repos keep .git as a file; plain checkouts still have a .git entry
  throw "Not a git repository root: $resolvedRepoRoot (no .git entry)"
}
$protectedPathsPath = Join-Path $resolvedRepoRoot $ProtectedPathsFile
$tokenPath = Join-Path $resolvedRepoRoot ".control-plane/.governance-approval.json"
$auditPath = Join-Path $resolvedRepoRoot ".control-plane/.governance-audit.jsonl"

# The directory is untracked local state and may not exist on a fresh clone;
# both the token and the audit write below would fail without it.
$controlPlaneDir = Join-Path $resolvedRepoRoot ".control-plane"
if (-not (Test-Path -LiteralPath $controlPlaneDir)) {
  New-Item -ItemType Directory -Path $controlPlaneDir -Force | Out-Null
}

function Normalize-RepoPath {
  param([string]$Path)
  $normalized = $Path.Replace("\", "/")
  if ($normalized.StartsWith("./", [System.StringComparison]::Ordinal)) {
    $normalized = $normalized.Substring(2)
  }
  return $normalized
}

Push-Location $resolvedRepoRoot
try {
  $protected = @()
  if (Test-Path -LiteralPath $protectedPathsPath) {
    $config = Get-Content -LiteralPath $protectedPathsPath -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($null -ne $config.protectedPaths) {
      $protected = @($config.protectedPaths)
    }
  }
  if ($protected.Count -eq 0) {
    $protected = @("governance/", "AGENTS.md", "AI_BOOTSTRAP.md")
  }

  $stagedFiles = @(& git diff --cached --name-only --diff-filter=ACMR)
  if ($LASTEXITCODE -ne 0) {
    throw "git diff --cached failed"
  }

  if ($stagedFiles.Count -eq 0) {
    [Console]::Error.WriteLine("ALARM [approve]: no staged files at all. Staging is empty — nothing was approved.")
    [Console]::Error.WriteLine("Fix: git add <files> first, then re-run this script from the repo root (or pass -RepoRoot).")
    exit 1
  }

  $approvedFiles = New-Object System.Collections.Generic.List[string]
  foreach ($file in $stagedFiles) {
    $normalizedFile = Normalize-RepoPath -Path $file
    foreach ($pattern in $protected) {
      $normalizedPattern = Normalize-RepoPath -Path ([string]$pattern)
      if ([string]::IsNullOrWhiteSpace($normalizedPattern)) { continue }
      $isDirectoryPattern = $normalizedPattern.EndsWith("/")
      $matches = if ($isDirectoryPattern) {
        $normalizedFile.StartsWith($normalizedPattern, [System.StringComparison]::OrdinalIgnoreCase)
      } else {
        $normalizedFile.Equals($normalizedPattern, [System.StringComparison]::OrdinalIgnoreCase)
      }
      if ($matches) { $approvedFiles.Add($normalizedFile) | Out-Null }
    }
  }

  if ($approvedFiles.Count -eq 0) {
    [Console]::Error.WriteLine("ALARM [approve]: staged files exist but NONE match a protected path.")
    [Console]::Error.WriteLine("Staged: $($stagedFiles -join ', ')")
    [Console]::Error.WriteLine("Protected patterns: $($protected -join ', ')")
    [Console]::Error.WriteLine("Fix: pass -RepoRoot pointing at the repo whose staged set you mean, or stage protected files first.")
    exit 1
  }

  $token = [guid]::NewGuid().ToString("N")
  $now = Get-Date
  $expires = $now.AddMinutes($TtlMinutes)

  # Bind staged BLOB hashes (git object SHA-1 as recorded in the index) so
  # content changed after approval invalidates the token at consume time.
  $blobHashes = [ordered]@{}
  foreach ($f in ($approvedFiles | Select-Object -Unique)) {
    $ls = & git ls-files -s -- $f
    if ($LASTEXITCODE -ne 0) { throw "git ls-files failed for $f" }
    $parts = $ls -split "\s+"
    if ($parts.Count -ge 2) { $blobHashes[$f] = $parts[1] }
  }

  $payload = [ordered]@{
    token = $token
    createdAt = $now.ToString("o")
    expiresAt = $expires.ToString("o")
    approvedFiles = @($approvedFiles | Select-Object -Unique)
    blobHashes = $blobHashes
    approvedBy = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
  }

  $payload | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $tokenPath -Encoding utf8

  # Append-only audit record (machine evidence about the approval itself).
  $auditLine = [ordered]@{
    event = "approval_granted"
    timestamp = $now.ToString("o")
    token = $token
    expiresAt = $expires.ToString("o")
    approvedFiles = @($approvedFiles | Select-Object -Unique)
    blobHashes = $blobHashes
    approvedBy = $payload.approvedBy
  } | ConvertTo-Json -Compress -Depth 8
  Add-Content -LiteralPath $auditPath -Value $auditLine -Encoding utf8

  Write-Output "Governance approval granted for $($approvedFiles.Count) file(s), expires in $TtlMinutes minute(s):"
  foreach ($f in ($approvedFiles | Select-Object -Unique)) { Write-Output " - $f" }
  Write-Output "Audit: $auditPath"
  Write-Output "L1 sequence: run 'git commit' NOW - single-use token, no git commands in between."
} finally {
  Pop-Location
}
